### ISSUE TITLE
Can't build on linux 

### ISSUE THREAD

**Issue by felipetesc** [maxdeviant/gpui-playground#1]
## Expected Behavior

See a window rendering the ui 

## Actual Behavior

Terminal prints:
error: failed to run command for `gpu v0.1.0 ...` 

## Steps to Reproduce the Problem

  1. Open terminal
  2. Type cargo run --release
  3. Check for output

## Specifications

  - Version: 0.1.0
  - Platform: Archlinux 
  - Subsystem: KDE 6

## How to Fix: 
Replace the cargo entry:
```bash
gpui = { git = "https://github.com/zed-industries/zed.git", rev = "90c1d8f734615552297a65e12dd430bf0825cdb0" }
```
to:

```bash
gpui = { git = "https://github.com/zed-industries/zed/" }`
```

**Comment by maxdeviant** [comment]
This is just a playground for me to play around with GPUI.

It's not an official Zed or GPUI project.
