### ISSUE TITLE
Suggestion: Create a template

### ISSUE THREAD

**Issue by felipetesc** [maxdeviant/gpui-playground#2]
I wanted to suggest to change the the hello_world folder name to gui, or something like this, replace the main.rs file with the code from https://www.gpui.rs/ : 
```rust
use gpui::*;
 
struct HelloWorld {
    text: SharedString,
}
 
impl Render for HelloWorld {
    fn render(&mut self, _cx: &mut ViewContext<Self>) -> impl IntoElement {
        div()
            .flex()
            .bg(rgb(0x2e7d32))
            .size_full()
            .justify_center()
            .items_center()
            .text_xl()
            .text_color(rgb(0xffffff))
            .child(format!("Hello, {}!", &self.text))
    }
}
 
fn main() {
    App::new().run(|cx: &mut AppContext| {
        cx.open_window(WindowOptions::default(), |cx| {
            cx.new_view(|_cx| HelloWorld {
                text: "World".into(),
            })
        });
    });
}
```

And to create a template from this rep. 
I could do that, but since this rep do almost the same, we can have a single place for gpui templates. 
Thanks!

**Comment by maxdeviant** [comment]
This is just a playground for me to play around with GPUI.

It's not an official Zed or GPUI project.

**Comment by maxdeviant** [comment]
This is just a playground for me to play around with GPUI.

It's not an official Zed or GPUI project.

**Comment by felipetesc** [comment]
> This is just a playground for me to play around with GPUI.
> 
> It's not an official Zed or GPUI project.

When I searched for the tag gpui on Github your project offered the most straightforward  way to start a new project using GPUI, but, yes, I see your point.
